baseURL = "https://findmytrueself.github.io/"
languageCode = "en-us"
title = "Hun's Blog âœï¸"
theme = "archie"
copyright = "Â© Im Hun"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[taxonomies]
  category = "categories"
  tag = "tags"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  mode="auto"
  author = { name = "Im Hun" }
  defaultTheme = "auto"
  title = "Hun's Blog"
  description = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„±ì¥ê¸°"
  keywords = ["Blog", "Portfolio", "archie"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "ì•ˆë…•í•˜ì„¸ìš”. ğŸ‘‹"
    Content = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„í›ˆ ì…ë‹ˆë‹¤ :)"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/findmytrueself"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/instant.coffee_"

  [params.analytics]
    google = { SiteVerificationTag = "XYZabc" }
    bing = { SiteVerificationTag = "XYZabc" }
    yandex = { SiteVerificationTag = "XYZabc" }

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "POSTS"
  name = "POSTS"
  url = "/posts"
  weight = 30

[[menu.main]]
  identifier = "LIFE"
  name = "LIFE"
  url = "/life"
  weight = 30

[[menu.main]]
  identifier = "TAGS"
  name = "TAGS"
  url = "/tags"
  weight = 30

[[menu.main]]
  identifier = "RESUME"
  name = "RESUME"
  url = "/pdfs/3ë…„ì°¨_í”„ë¡ íŠ¸ì—”ë“œ_ì„í›ˆ.pdf"
  weight = 30