baseURL = "https://findmytrueself.github.io/"
languageCode = "ko"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
paginate = 3
title = "Hun's Blog âœï¸"
theme = "tailwind"
author = "Im Hun"
copyright = "Im Hun"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
disqusShortname = "https-findmytrueself-github-io"


[languages]
  [languages.ko]
    languageName = "í•œêµ­ì–´"
    weight = 1
    contentDir = "content/ko"

    [languages.ko.menu]
    [[languages.ko.menu.main]]
    identifier = "ALGORITHM"
    name = "ALGORITHM"
    url = "/ko/algorithm"
    weight = 1

    [[languages.ko.menu.main]]
    identifier = "BLOCKCHAIN"
    name = "BLOCKCHAIN"
    url = "/ko/blockchain"
    weight = 2

    [[languages.ko.menu.main]]
    identifier = "FRONTEND"
    name = "FRONTEND"
    url = "/ko/frontend"
    weight = 3

    [[languages.ko.menu.main]]
    identifier = "DIARY"
    name = "DIARY"
    url = "/ko/diary"
    weight = 4

    [[languages.ko.menu.main]]
    identifier = "RÃ©sumÃ©.pdf"
    name = "RÃ©sumÃ©.pdf"
    url = "/pdfs/í”„ë¡ íŠ¸ì—”ë“œ_ì„í›ˆ.pdf"
    weight = 5

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

    [languages.en.menu]
    [[languages.en.menu.main]]
    identifier = "ALGORITHM"
    name = "ALGORITHM"
    url = "/en/algorithm"
    weight = 1

    [[languages.en.menu.main]]
    identifier = "BLOCKCHAIN"
    name = "BLOCKCHAIN"
    url = "/en/blockchain"
    weight = 2

    [[languages.en.menu.main]]
    identifier = "FRONTEND"
    name = "FRONTEND"
    url = "/en/frontend"
    weight = 3

    [[languages.en.menu.main]]
    identifier = "DIARY"
    name = "DIARY"
    url = "/en/diary"
    weight = 4

    [[languages.en.menu.main]]
    identifier = "RÃ©sumÃ©.pdf"
    name = "RÃ©sumÃ©.pdf"
    url = "/pdfs/frontend_developer.pdf"
    weight = 5

[markup]
  _merge = "deep"

[outputs]
  home = ["HTML", "RSS", "Sitemap"]


[taxonomies]
  category = "categories"
  tag = "tags"

[minify]
  disableXML = true
  minifyOutput = true

[params.header]
    logo = "/images/gamer.png"

[params.footer]
    since = 2024
    poweredby = false


[params]
  mode = "toggle"
  useCDN = true
  defaultTheme = "auto" 
  subtitle = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„±ì¥ê¸°"
  keywords = ["Blog", "Portfolio", "archie"]
  author = "Im Hun"
  og_image = "/images/gamer.png"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "ì•ˆë…•í•˜ì„¸ìš”. ğŸ‘‹"
    Content = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„í›ˆ ì…ë‹ˆë‹¤ :)"



  [[params.social_media.items]]
  enabled = true
  title = "GitHub"
  icon = "brand-github"
  link = "https://github.com/findmytrueself"

  [[params.social_media.items]]
  enabled = true
  title = "Instagram"
  icon = "brand-instagram"
  link = "https://instagram.com/instant.coffee_"

  [[params.social_media.items]]
  enabled = true
  title = "LinkedIn"
  icon = "brand-linkedin"
  link = "https://www.linkedin.com/in/findmytrueself"

  [params.analytics]
    google = { SiteVerificationTag = "XYZabc" }
    bing = { SiteVerificationTag = "XYZabc" }
    yandex = { SiteVerificationTag = "XYZabc" }

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
