baseURL = "https://findmytrueself.github.io/"
languageCode = "en"
paginate = 3
title = "Hun's Blog âœï¸"
theme = "tailwind"
author = "Im Hun"
copyright = "Im Hun"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
disqusShortname = "https-findmytrueself-github-io"

[markup]
  _merge = "deep"

[outputs]
  home = ["HTML", "RSS", "Sitemap"]

[taxonomies]
  category = "categories"
  tag = "tags"

[minify]
  disableXML = true
  minifyOutput = true

[params.header]
    logo = "/images/gamer.png"

[params.footer]
    since = 2024
    poweredby = false


[params]
  mode = "toggle"
  useCDN = true
  defaultTheme = "auto" 
  subtitle = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„±ì¥ê¸°"
  keywords = ["Blog", "Portfolio", "archie"]
  author = "Im Hun"
  og_image = "/images/gamer.png"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "ì•ˆë…•í•˜ì„¸ìš”. ğŸ‘‹"
    Content = "í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì ì„í›ˆ ì…ë‹ˆë‹¤ :)"

  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/findmytrueself"

  [[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https://instagram.com/instant.coffee_"

  [params.analytics]
    google = { SiteVerificationTag = "XYZabc" }
    bing = { SiteVerificationTag = "XYZabc" }
    yandex = { SiteVerificationTag = "XYZabc" }

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "POSTS"
  name = "POSTS"
  url = "/posts"
  weight = 30

[[menu.main]]
  identifier = "LIFE"
  name = "LIFE"
  url = "/life"
  weight = 30

[[menu.main]]
  identifier = "RESUME ğŸ“"
  name = "RESUME ğŸ“"
  url = "/pdfs/3ë…„ì°¨_í”„ë¡ íŠ¸ì—”ë“œ_ì„í›ˆ.pdf"
  weight = 30